{{- if and (not .Values.app.existingSecret) (or .Values.app.sharedPassword .Values.app.superAdminPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-quiz.fullname" . }}
  labels:
    {{- include "team-quiz.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.app.sharedPassword }}
  shared-password: {{ .Values.app.sharedPassword | quote }}
  {{- end }}
  {{- if .Values.app.superAdminPassword }}
  super-admin-password: {{ .Values.app.superAdminPassword | quote }}
  {{- end }}
{{- end }}
